[package]
name = "rust-snes"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
dirs = "5.0.1"
env_logger = "0.11.5"
log = "0.4.22"
modular-bitfield = "0.11.2"
sdl2 = "0.37.0"

[dev-dependencies]
image = "0.23.3"
